version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  database:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


